### ISSUE TITLE
aclpolicy template is not rendered properly

### ISSUE THREAD

**Issue by vkhatri** [criteo-cookbooks/rundeck-server#14]
```sh
#
# This file is generated by Chef
#
---
description: Admin, all access.
context: !ruby/hash:Chef::Node::ImmutableMash
  project: .*
for: !ruby/hash:Chef::Node::ImmutableMash
  resource: !ruby/array:Chef::Node::ImmutableArray
  - !ruby/hash:Chef::Node::ImmutableMash
    allow: '*'
  adhoc: !ruby/array:Chef::Node::ImmutableArray
  - !ruby/hash:Chef::Node::ImmutableMash
    allow: '*'
  job: !ruby/array:Chef::Node::ImmutableArray
  - !ruby/hash:Chef::Node::ImmutableMash
    allow: '*'
  node: !ruby/array:Chef::Node::ImmutableArray
  - !ruby/hash:Chef::Node::ImmutableMash
    allow: '*'
by: !ruby/hash:Chef::Node::ImmutableMash
  group: !ruby/array:Chef::Node::ImmutableArray
  - admin

---
description: Admin, all access.
context: !ruby/hash:Chef::Node::ImmutableMash
  application: rundeck
for: !ruby/hash:Chef::Node::ImmutableMash
  resource: !ruby/array:Chef::Node::ImmutableArray
  - !ruby/hash:Chef::Node::ImmutableMash
    allow: '*'
  project: !ruby/array:Chef::Node::ImmutableArray
  - !ruby/hash:Chef::Node::ImmutableMash
    allow: '*'
  storate: !ruby/array:Chef::Node::ImmutableArray
  - !ruby/hash:Chef::Node::ImmutableMash
    allow: '*'
by: !ruby/hash:Chef::Node::ImmutableMash
  group: !ruby/array:Chef::Node::ImmutableArray
  - admin
```

will submit a PR.

**Comment by rveznaver** [comment]
Hi @vkhatri, this seems very strange. What version of Chef are you using?

**Comment by vkhatri** [comment]
@rveznaver please find chef server/client versions below

```ruby
client: chef-11.8.2-1.el6.x86_64
server: chef-server-11.1.6-1.el6.x86_64
```

**Comment by rveznaver** [comment]
Hi @vkhatri, this is a Chef bug that was fixed in 11.12.0 ([CHEF-5132](https://tickets.opscode.com/browse/CHEF-5132)). I have tested the cookbook in kitchen with Chef 11.12.0 and did not run into this.

**Comment by vkhatri** [comment]
@rveznaver thank you for looking into this, i should have noticed that.

i will update the PR for Chef version dependency.

**Comment by isuftin** [comment]
FYI this has also appeared again in at least version 13.0.113 of the Chef client:

```
#
# This file is generated by Chef
#
---
description: Admin, all access.
context: !ruby/hash:Mash
  project: ".*"
for: !ruby/hash:Mash
  resource:
  - !ruby/hash:Mash
    allow: "*"
  adhoc:
  - !ruby/hash:Mash
    allow: "*"
  job:
  - !ruby/hash:Mash
    allow: "*"
  node:
  - !ruby/hash:Mash
    allow: "*"
by: !ruby/hash:Mash
  group:
  - admin

---
description: Admin, all access.
context: !ruby/hash:Mash
  application: rundeck
for: !ruby/hash:Mash
  resource:
  - !ruby/hash:Mash
    allow: "*"
  project:
  - !ruby/hash:Mash
    allow: "*"
  storage:
  - !ruby/hash:Mash
    allow: "*"
by: !ruby/hash:Mash
  group:
  - admin
```
