### ISSUE TITLE
Exclamation marks in ACL policies generated from attributes

### ISSUE THREAD

**Issue by scopenco** [criteo-cookbooks/rundeck-server#58]
Chef 13.1.31 generate wrong ACL policies based on attributes:

```
#
# This file is generated by Chef
#
---
description: Admin, all access.
context: !ruby/hash:Mash
  project: ".*"
for: !ruby/hash:Mash
  resource:
  - !ruby/hash:Mash
    allow: "*"
  adhoc:
  - !ruby/hash:Mash
    allow: "*"
  job:
  - !ruby/hash:Mash
    allow: "*"
  node:
  - !ruby/hash:Mash
    allow: "*"
by: !ruby/hash:Mash
```

The hack in `aclpolicy.erb` that should fix these exclamation marks doesn't work now.

Rundeck 2.8.2

error:
```
Can't construct a java object for tag:yaml.org,2002:com.dtolabs.rundeck.core.authorization.providers.yaml.model.ACLPolicyDoc; exception=Cannot create property=context for JavaBean=Policy{context=null, description='Admin, all access.', for=null, by=null, id='null'}; null; Can't construct a java object for !ruby/hash:Mash; exception=Invalid tag: !ruby/hash:Mash
 in "<reader>", line 5, column 1:
    description: Admin, all access.
    ^
```
